small_model_config = {
    "seq_len": 64,
    "vocab_size": 10000,
    "high_level_cycles": 2,
    "low_level_cycles": 2,
    "num_layers": 2,
    "hidden_size": 64,
    "num_heads": 4,
    "expansion": 2.0,
    "norm_epsilon": 1e-5,
    "rope_theta": 10000.0,
    "halt_max_steps": 4,
    "halt_exploration_prob": 0.05,
    "batch_size": 2,
    "n_epochs": 1,
}

small_training_config = {
    "batch_size": 4,
    "n_epochs": 2,
    "lr": 5e-4,
    "warmup_steps": 100,
    "clip_norm": 1.0,
    "model_path": "hrm_model_small.pth",
    "sample_frequency": 0.01,
    "weight_decay": 0.01,
    "beta1": 0.9,
    "beta2": 0.99,
    "eval_interval": 10,
    "checkpoint_every_eval": False,
    "max_segments": 2,
    "halt_max_steps": 4,
    "halt_exploration_prob": 0.05,
}
